export const UrlConstants = {
  LOGIN: "/login",
  REGITER: "/regiter",
  HOME: "/admin",
  USER_LIST: "/admin/users",
  USER_ADD: "/admin/user-add",
  USER_EDIT: "/admin/user-edit",
  PRODUCT_TYPE_LIST: "/admin/product-types",
  PRODUCT_TYPE_ADD: "/admin/product-type-add",
  PRODUCT_TYPE_EDIT: "/admin/product-type-edit",
  PRODUCT_LIST: "/admin/products",
  PRODUCT_ADD: "/admin/product-add",
  PRODUCT_EDIT: "/admin/product-edit",
  PRODUCT_DETAIL: "/admin/product-detail",
};
